# Generated by Django 3.0.6 on 2022-12-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(db_column='CODUSUARIO', max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBREUSUARIO', max_length=100)),
                ('clave', models.CharField(max_length=100)),
                ('es_supervisor', models.BooleanField(db_column='BANDSUPERVISOR')),
                ('is_active', models.BooleanField(db_column='BANDVALIDA')),
                ('modulos', models.CharField(max_length=200)),
                ('last_login', models.DateTimeField(db_column='FECHAGRABADO')),
                ('BandSupervisor', models.CharField(max_length=10)),
                ('BandValida', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'USUARIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.CharField(db_column='CODEMPRESA', max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('tipo_base_datos', models.IntegerField(db_column='TIPODB')),
                ('nombre_base_datos', models.CharField(db_column='NOMBREDB', max_length=20)),
                ('server', models.CharField(max_length=30)),
                ('usuario', models.CharField(db_column='USERNAME', max_length=20)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'EMPRESA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoUsuario',
            fields=[
                ('CodGrupo', models.CharField(db_column='CodGrupo', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'GRUPO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('Id', models.IntegerField(db_column='Id', primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'PERMISO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermisoMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(db_column='PARAM', max_length=20)),
            ],
            options={
                'db_table': 'PERMISOMENU',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermisoTrans',
            fields=[
                ('IdPermiso', models.IntegerField(db_column='IdPermiso', primary_key=True, serialize=False, unique=True)),
                ('CodTrans', models.CharField(max_length=10)),
                ('Crear', models.BooleanField(default=True, null=True)),
                ('Ver', models.BooleanField(default=True, null=True)),
                ('Modificar', models.BooleanField(default=True, null=True)),
                ('Eliminar', models.BooleanField(default=True, null=True)),
                ('Aprobar', models.BooleanField(default=True, null=True)),
                ('Desaprobar', models.BooleanField(default=True, null=True)),
                ('Despachar', models.BooleanField(default=True, null=True)),
                ('Anular', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'PermisoTrans',
                'permissions': (('PermisoTrans', 'Puede visualizar PermisoTrans'),),
                'managed': False,
            },
        ),
    ]
